import codecs
import re

mdFileUrl = 'test.md'
outData = []
htmlStart = '''<!DOCTYPE HTML>
<html lang='en'>
<head>
  <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
  <link rel='stylesheet' href='markflip.css' type='text/css' />
  <title>Generated by MarkFlip</title>
</head>
<body>
'''
htmlEnd = '''</body>
</html>
'''

headerRegex = re.compile(r'(#{1,6} *)(.*)')
strongRegex = re.compile(r'\*{2}.+\*{2}')
emphasisRegex = re.compile(r'[^\*\\]\*[^/]+[^\\]\*[^\*]')
strikeRegex = re.compile(r'~{2}.+~{2}')

with codecs.open(mdFileUrl,'r','utf-8') as f:
    raw = f.read()
    for level, text in headerRegex.findall(raw):
        originalText = level+text
        level = level.count('#')
        raw = raw.replace(originalText, '<h{}>{}</h{}>'.format(level,text,level))
    for match in strongRegex.findall(raw):
        raw = raw.replace(match, '<strong>{}</strong>'.format(match[2:-2]))
    for match in emphasisRegex.findall(raw):
        raw = raw.replace(match[1:-1], '<em>{}</em>'.format(match[2:-2]))
    for match in strikeRegex.findall(raw):
        raw = raw.replace(match, '<del>{}</del>'.format(match[2:-2]))
    raw = raw.replace('\*','*')
    raw = raw.replace('\n\n','<br /><br />')
    raw = raw.replace('\n','')

with codecs.open('MarkFlip.html','w','utf-8') as f:
    f.write(htmlStart)
    f.write(raw)
    f.write(htmlEnd)
